/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandLogo: typeof import('./src/components/TopBar/BrandLogo.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    DummyComponent: typeof import('./src/components/DummyComponent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginDialog: typeof import('./src/components/TopBar/LoginDialog.vue')['default']
    Navigation: typeof import('./src/components/TopBar/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskForm: typeof import('./src/components/TaskForm.vue')['default']
    TaskItem: typeof import('./src/components/TaskItem.vue')['default']
    TaskManager: typeof import('./src/components/TaskManager.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UserSection: typeof import('./src/components/TopBar/UserSection.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
